
---
- name: Install and deploy Flask app in Docker
  hosts: ec2
  become: true

  vars:
    app_dir: /home/ec2-user/flask_app

  tasks:
    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy application files
      copy:
        src: files/
        dest: "{{ app_dir }}"
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Build Docker image
      command: docker build -t flask-app .
      args:
        chdir: "{{ app_dir }}"
      become: true

    - name: Stop old container (if running)
      shell: docker ps -q --filter "name=flask-app" | xargs -r docker stop
      ignore_errors: yes

    - name: Remove old container (if exists)
      shell: docker ps -aq --filter "name=flask-app" | xargs -r docker rm
      ignore_errors: yes

    - name: Run Flask Docker container
      command: docker run -d -p 80:80 --name flask-app flask-app


